### ISSUE TITLE
Eine Frage

### ISSUE THREAD

**Issue by blakedj012** [StylexTV/LYNX#3]
Wann gedenkst Du denn mal Gsigns zu updaten? Ist das Project jetzt tot oder machst Du da noch weiter?

Es gibt keine bessere Alternative zu deinem Plugin und viele Leute warten auf ein Update. Sämtliche Kontaktmöglichkeiten von Dir incl. Discord sind nicht möglich.

Es wäre sehr sehr schade wenn Du an Gsigns nicht weitermachst. Bitte bring ein Update für die 1.17.x. Ich denke mal es ist keine große Sache.

**Comment by StylexTV** [comment]
Sorry, ich habe die Entwicklung von GSigns beendet. Das Plugin ist jedoch Open-Source und ich habe kein Problem damit, wenn jemand anderes meine Arbeit fortsetzt (vorausgesetzt, jemand stellt sich zur Verfügung).

**Comment by blakedj012** [comment]
Nimm mich mal im Discord bitte an. Hier nochmal meine ID Punkylord#7906


Am So., 22. Aug. 2021 um 10:31 Uhr schrieb StylexTV <
***@***.***>:

**Comment by StylexTV** [comment]
Nein, es gibt nichts mehr zu klären. Die Entwicklung von Minecraft-Plugins hat zu viel Zeit in Anspruch genommen und so habe ich aufgehört.

**Comment by blakedj012** [comment]
Ich donate dich dafür ! Ich brauche diese Plugin

**Comment by StylexTV** [comment]
Ich habe weder finanzielle Nöte, noch würde mich Geld motivieren, etwas zu entwickeln. Außerdem bin ich sicher, dass du eine Alternative zu meinem Plugin finden kannst.

**Comment by blakedj012** [comment]
Es gibt wirklich keine Alternative. Gar keine mit diesen Möglichkeiten gerade was TextRendering angeht. Mensch Du hast es als Premium Ressource gemacht warum hast Du das Ende dann noch nicht auf Spigot kommuniziert? Es gibt sicher einige die das Plugin gekauft haben. Ich denke das wäre nur fair auch den neuen Käufern gegenüber die erwarten das dieses Plugin weiterentwickelt wird. Ist doch schade ganz ehrlich das man sowas geniales aufgibt.

**Comment by blakedj012** [comment]
Zumal es nicht viel zu sein scheint um es auf der 1.17 lauffähig zu machen. siehe hier:
https://pastebin.com/AEp4h0eC

**Comment by StylexTV** [comment]
Wenn es angeblich nicht viel Arbeit ist, bin ich mir sicher, dass du jemanden finden kannst, der die Arbeit für dich und die anderen erledigt (es ist allerdings ein bisschen mehr Arbeit als du dir vorstellst).

**Comment by blakedj012** [comment]
Dann mach es bitte. Ich donate 50€ für das Update!

**Comment by StylexTV** [comment]
Nein danke, bitte lass' mich in Ruhe!

**Comment by blakedj012** [comment]
Dann sei bitte so fair und gebe das offizielle Ende auf der Spigotseite bekannt!

**Comment by StylexTV** [comment]
Ok, ist geschehen.

**Comment by blakedj012** [comment]
Danke..... Auf Wiedersehen...
